services:
  blog:
    build:
      context: blog
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - ./blog/content:/src/content
      - ./blog/hugo.toml:/src/hugo.toml
      - ./data:/data

  crawler:
    build:
      context: crawler
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./crawler/sources.json:/app/sources.json
    profiles: ["crawler"]
